[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

[rpc_endpoints]
fluent_devnet = "https://rpc.dev.gblend.xyz"

[etherscan]
fluent_devnet = { key = "dummy", url = "https://blockscout.dev.gblend.xyz/api/" }
